apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: actions-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner
  namespace: actions-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/attach"]
    verbs: ["create", "get", "list", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner
  namespace: actions-runner
subjects:
  - kind: ServiceAccount
    name: github-runner
    namespace: actions-runner
roleRef:
  kind: Role
  name: github-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: github-runner
  namespace: actions-runner
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
type: Opaque
stringData:
  ACCESS_TOKEN: "CHANGE_ME"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: actions-runner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      containers:
        - name: runner
          image: myoung34/github-runner:latest
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 4Gi
          env:
            - name: BUILDAH_ISOLATION
              value: chroot
            - name: STORAGE_DRIVER
              value: overlay
            - name: CONTAINERS_CONF
              value: /dev/null
            - name: REPO_URL
              value: "https://github.com/ryanavilar/workshop-akasha"
            - name: RUNNER_SCOPE
              value: "repo"
            - name: RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RUNNER_WORKDIR
              value: /tmp/runner
            - name: LABELS
              value: "self-hosted,linux,workshop"
            - name: EPHEMERAL
              value: "true"
          envFrom:
            - secretRef:
                name: github-runner
          volumeMounts:
            - name: work
              mountPath: /tmp/runner
            - name: buildah-cache
              mountPath: /var/lib/containers
      volumes:
        - name: work
          emptyDir: {}
        - name: buildah-cache
          emptyDir: {}
