apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workshop-db.yaml
  - vikunja.yaml
  - workshop-db-scheduled-backup.yaml
  - github-runner.yaml
  - workshop-db-user.yaml
  - workshop-db-backup-s3.yaml
