name: Build and Push Vikunja

on:
  push:
    branches: [main]
    paths:
      - "apps/vikunja/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, workshop]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          buildah build \
            --format docker \
            -t zot-workshop-akasha.cl8s.dev/vikunja/vikunja:${{ github.sha }} \
            -t zot-workshop-akasha.cl8s.dev/vikunja/vikunja:latest \
            apps/vikunja/

      - name: Push to Zot
        run: |
          buildah push --tls-verify=false \
            zot-workshop-akasha.cl8s.dev/vikunja/vikunja:${{ github.sha }}
          buildah push --tls-verify=false \
            zot-workshop-akasha.cl8s.dev/vikunja/vikunja:latest
